"""add fields to projects

Revision ID: 2bf29638d237
Revises: 
Create Date: 2026-05-04 15:54:51.056349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf29638d237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'edited_at')
    op.drop_column('projects', 'duration')
    op.drop_column('projects', 'company_id')
    # ### end Alembic commands ###
