"""sync tasks table

Revision ID: d6441d8a6770
Revises: 2bf29638d237
Create Date: 2026-05-07 12:28:54.855999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6441d8a6770'
down_revision: Union[str, Sequence[str], None] = '2bf29638d237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('task_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_status')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###
